// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nillion/meta/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/cosmos-sdk/x/bank/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgPayFor defines the Msg/PayFor request type.
type MsgPayFor struct {
	Resource    []byte                                   `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	FromAddress string                                   `protobuf:"bytes,2,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	Amount      github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=amount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amount"`
}

func (m *MsgPayFor) Reset()         { *m = MsgPayFor{} }
func (m *MsgPayFor) String() string { return proto.CompactTextString(m) }
func (*MsgPayFor) ProtoMessage()    {}
func (*MsgPayFor) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c2b216208307c1, []int{0}
}
func (m *MsgPayFor) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPayFor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPayFor.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPayFor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPayFor.Merge(m, src)
}
func (m *MsgPayFor) XXX_Size() int {
	return m.Size()
}
func (m *MsgPayFor) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPayFor.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPayFor proto.InternalMessageInfo

func (m *MsgPayFor) GetResource() []byte {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *MsgPayFor) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *MsgPayFor) GetAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Amount
	}
	return nil
}

// MsgPayForResponse defines the Msg/PayFor response type.
type MsgPayForResponse struct {
}

func (m *MsgPayForResponse) Reset()         { *m = MsgPayForResponse{} }
func (m *MsgPayForResponse) String() string { return proto.CompactTextString(m) }
func (*MsgPayForResponse) ProtoMessage()    {}
func (*MsgPayForResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5c2b216208307c1, []int{1}
}
func (m *MsgPayForResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPayForResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPayForResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPayForResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPayForResponse.Merge(m, src)
}
func (m *MsgPayForResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgPayForResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPayForResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPayForResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgPayFor)(nil), "nillion.meta.v1.MsgPayFor")
	proto.RegisterType((*MsgPayForResponse)(nil), "nillion.meta.v1.MsgPayForResponse")
}

func init() { proto.RegisterFile("nillion/meta/v1/tx.proto", fileDescriptor_b5c2b216208307c1) }

var fileDescriptor_b5c2b216208307c1 = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x31, 0x6f, 0x13, 0x31,
	0x14, 0xc7, 0x73, 0x44, 0x44, 0xf4, 0x1a, 0x09, 0xe5, 0xa8, 0xc4, 0xf5, 0x86, 0x6b, 0x94, 0x29,
	0xaa, 0x14, 0x5b, 0x29, 0x4c, 0x30, 0x11, 0xa4, 0x8a, 0xa5, 0x11, 0x0a, 0x12, 0x03, 0x4b, 0xe4,
	0x5c, 0x8c, 0x6b, 0x25, 0xf6, 0x8b, 0xfc, 0x9c, 0xd0, 0x6c, 0x88, 0x4f, 0xc0, 0xcc, 0x27, 0x40,
	0x4c, 0x1d, 0xf8, 0x10, 0x1d, 0x2b, 0x26, 0x26, 0x40, 0xc9, 0xd0, 0x9d, 0x4f, 0x80, 0x7c, 0x76,
	0x4f, 0x11, 0x88, 0xe5, 0xee, 0x9e, 0x7f, 0xfe, 0xff, 0xfd, 0xfe, 0x7e, 0x17, 0xa7, 0x5a, 0xce,
	0xe7, 0x12, 0x34, 0x55, 0xdc, 0x32, 0xba, 0xea, 0x53, 0x7b, 0x41, 0x16, 0x06, 0x2c, 0x24, 0xf7,
	0x03, 0x21, 0x8e, 0x90, 0x55, 0x3f, 0x3b, 0x10, 0x20, 0xa0, 0x64, 0xd4, 0x7d, 0xf9, 0x6d, 0x59,
	0x5e, 0x00, 0x2a, 0x40, 0x3a, 0x61, 0xc8, 0xe9, 0xaa, 0x3f, 0xe1, 0x96, 0xf5, 0x69, 0x01, 0x52,
	0xff, 0xc3, 0xf5, 0xac, 0xe2, 0xae, 0x08, 0xfc, 0xd0, 0xf3, 0xb1, 0x37, 0xf6, 0x45, 0x40, 0x0f,
	0x83, 0x54, 0xa1, 0x70, 0x9d, 0x29, 0x14, 0x01, 0xb4, 0x98, 0x92, 0x1a, 0x68, 0xf9, 0xf4, 0x4b,
	0x9d, 0xdf, 0x51, 0xbc, 0x77, 0x86, 0xe2, 0x25, 0x5b, 0x9f, 0x82, 0x49, 0xb2, 0xf8, 0x9e, 0xe1,
	0x08, 0x4b, 0x53, 0xf0, 0x34, 0x6a, 0x47, 0xdd, 0xe6, 0xa8, 0xaa, 0x93, 0xa7, 0x71, 0xf3, 0xad,
	0x01, 0x35, 0x66, 0xd3, 0xa9, 0xe1, 0x88, 0xe9, 0x9d, 0x76, 0xd4, 0xdd, 0x1b, 0xa4, 0xdf, 0xbe,
	0xf6, 0x0e, 0xc2, 0xe9, 0xcf, 0x3c, 0x79, 0x65, 0x8d, 0xd4, 0x62, 0xb4, 0xef, 0x76, 0x87, 0xa5,
	0x64, 0x1d, 0x37, 0x98, 0x82, 0xa5, 0xb6, 0x69, 0xbd, 0x5d, 0xef, 0xee, 0x9f, 0x1c, 0x92, 0xa0,
	0x71, 0xf1, 0x49, 0x88, 0x47, 0x9e, 0x83, 0xd4, 0x83, 0xd3, 0xab, 0x1f, 0x47, 0xb5, 0x2f, 0x3f,
	0x8f, 0xba, 0x42, 0xda, 0xf3, 0xe5, 0x84, 0x14, 0xa0, 0x42, 0xbc, 0xf0, 0xea, 0xe1, 0x74, 0x46,
	0xed, 0x7a, 0xc1, 0xb1, 0x14, 0xe0, 0xa7, 0x9b, 0xcb, 0xe3, 0xe6, 0x9c, 0x0b, 0x56, 0xac, 0xc7,
	0xee, 0x02, 0xf1, 0xf3, 0xcd, 0xe5, 0x71, 0x34, 0x0a, 0x07, 0x3e, 0x69, 0x7d, 0x70, 0x7c, 0xb7,
	0xf5, 0xce, 0x83, 0xb8, 0x55, 0x65, 0x1e, 0x71, 0x5c, 0x80, 0x46, 0x7e, 0xf2, 0x3a, 0xae, 0x9f,
	0xa1, 0x48, 0x5e, 0xc4, 0x8d, 0xdb, 0xcb, 0x20, 0x7f, 0x4d, 0x92, 0x54, 0xa2, 0xac, 0xf3, 0x7f,
	0x76, 0x6b, 0x98, 0xdd, 0x7d, 0xef, 0xfa, 0x18, 0x0c, 0xaf, 0x36, 0x79, 0x74, 0xbd, 0xc9, 0xa3,
	0x5f, 0x9b, 0x3c, 0xfa, 0xb8, 0xcd, 0x6b, 0xd7, 0xdb, 0xbc, 0xf6, 0x7d, 0x9b, 0xd7, 0xde, 0x3c,
	0xde, 0x49, 0x38, 0xf4, 0x76, 0x43, 0x6e, 0xdf, 0x81, 0x99, 0xd1, 0xe0, 0xde, 0x2b, 0xce, 0x99,
	0xd4, 0xf4, 0xc2, 0xff, 0x65, 0x65, 0xe6, 0x49, 0xa3, 0x1c, 0xdc, 0xa3, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xfc, 0x39, 0x6e, 0xbc, 0x82, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// PayFor pays for a resource in the PET network
	PayFor(ctx context.Context, in *MsgPayFor, opts ...grpc.CallOption) (*MsgPayForResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) PayFor(ctx context.Context, in *MsgPayFor, opts ...grpc.CallOption) (*MsgPayForResponse, error) {
	out := new(MsgPayForResponse)
	err := c.cc.Invoke(ctx, "/nillion.meta.v1.Msg/PayFor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// PayFor pays for a resource in the PET network
	PayFor(context.Context, *MsgPayFor) (*MsgPayForResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) PayFor(ctx context.Context, req *MsgPayFor) (*MsgPayForResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayFor not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_PayFor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPayFor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PayFor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nillion.meta.v1.Msg/PayFor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PayFor(ctx, req.(*MsgPayFor))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nillion.meta.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PayFor",
			Handler:    _Msg_PayFor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nillion/meta/v1/tx.proto",
}

func (m *MsgPayFor) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPayFor) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPayFor) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		for iNdEx := len(m.Amount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Resource) > 0 {
		i -= len(m.Resource)
		copy(dAtA[i:], m.Resource)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Resource)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgPayForResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPayForResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPayForResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgPayFor) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Resource)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Amount) > 0 {
		for _, e := range m.Amount {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgPayForResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgPayFor) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPayFor: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPayFor: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Resource", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Resource = append(m.Resource[:0], dAtA[iNdEx:postIndex]...)
			if m.Resource == nil {
				m.Resource = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = append(m.Amount, types.Coin{})
			if err := m.Amount[len(m.Amount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPayForResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPayForResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPayForResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
